// Canonical Energy Public V2 planning adapter.
// Backend owns lane membership, energy quantities, boundary flows and balance.
function planningArray(value){const parsed=parseMaybeJson(value,value);return Array.isArray(parsed)?parsed:[];}
function planningParticipantId(row={}){return String(firstDefined(row.participant_id,row.asset_id,row.target_asset_id,row.flexible_asset_id,''));}
function planningEnergy(row={}){return asNumber(firstDefined(row.planned_demand_kwh,row.planned_supply_kwh,row.planned_energy_kwh,row.energy_kwh));}
function adaptPlanningBucket(bucket={},contractVersion=''){
  const required=['advisory_source_lane','advisory_consumer_lane','advisory_boundary_flows','advisory_lane_balance_delta_kwh'];
  const canonical=required.every(key=>Object.prototype.hasOwnProperty.call(bucket,key));
  if(!canonical)return {raw:bucket,id:String(firstDefined(bucket.bucket_id,bucket.id,'')),startTime:firstDefined(bucket.start_time,bucket.start,bucket.bucket_start,''),endTime:firstDefined(bucket.end_time,bucket.end,bucket.bucket_end,''),durationMinutes:asNumber(bucket.duration_minutes),sources:[],consumers:[],boundary:{gridExportKwh:null},balanceDeltaKwh:null,state:'unavailable',reason:'canonical_planning_lanes_not_published',confidence:'',forecastQuality:'',disclosure:'',canonicalLanes:false,contractSupported:false,contractFamily:'RHI_ENERGY_PUBLIC_CONTRACT_V2'};
  const normalize=(row,laneRole)=>({...row,participantId:planningParticipantId(row),laneRole,energyKwh:planningEnergy(row),powerKw:asNumber(firstDefined(row.planned_power_kw,row.power_kw,row.allocated_power_kw)),state:String(firstDefined(row.planning_state,row.state,row.status,'')||'').toLowerCase(),allocationState:String(firstDefined(row.allocation_state,'')||'').toLowerCase(),executionAllowed:firstDefined(row.plan_execution_allowed,null),reason:firstDefined(row.reason_label,row.user_reason_label,row.reason_code,row.reason,'')});
  const boundary=objectFrom(parseMaybeJson(bucket.advisory_boundary_flows,bucket.advisory_boundary_flows||{}));
  return {raw:bucket,id:String(firstDefined(bucket.bucket_id,bucket.id,'')),startTime:firstDefined(bucket.start_time,bucket.start,bucket.bucket_start,''),endTime:firstDefined(bucket.end_time,bucket.end,bucket.bucket_end,''),durationMinutes:asNumber(bucket.duration_minutes),sources:planningArray(bucket.advisory_source_lane).map(row=>normalize(row,'source')),consumers:planningArray(bucket.advisory_consumer_lane).map(row=>normalize(row,'consumer')),boundary:{gridExportKwh:asNumber(firstDefined(boundary.grid_export_kwh,boundary.export_kwh))},balanceDeltaKwh:asNumber(bucket.advisory_lane_balance_delta_kwh),state:String(firstDefined(bucket.planning_state,bucket.state,'')||'').toLowerCase(),reason:firstDefined(bucket.reason_label,bucket.reason_code,bucket.reason,''),confidence:firstDefined(bucket.confidence,''),forecastQuality:firstDefined(bucket.forecast_quality,''),disclosure:firstDefined(bucket.estimation_disclosure,''),canonicalLanes:true,contractSupported:true,contractFamily:'RHI_ENERGY_PUBLIC_CONTRACT_V2'};
}
if(typeof module!=='undefined'&&module.exports)module.exports={adaptPlanningBucket,planningEnergy};
